### PR TITLE
Deprecate the repository.

### PR DESCRIPTION
**Pull request by itsdalmo**
See https://github.com/TeliaSoneraNorge/telia-terraform-modules/blob/deprecate_repository/README.md

### CODE REVIEW

**Review by larstobi — APPROVED** [review]
I approve of this message! @itsdalmo

**Comment by glennbech** [comment]
excellent

**Review by colincoleman — APPROVED** [review]
Lets get this all in the right place :)

**Comment by itsdalmo** [comment]
https://github.com/telia-oss/terraform-modules <- What do you guys (@colincoleman, @glennbech and @larstobi) think of this name?

Personally, I think `terraform-aws-modules` is more descriptive, but unfortunately it clashes with Antons organisation. Question is, does that matter? Does anything matter? 🤔

**Pull request merged**
