### PR TITLE
ECS Fargate module

### PR DESCRIPTION
**Pull request by mikael-lindstrom**
Similar to `ecs/service` but instead runs on Fargate.

### CODE REVIEW

**Comment by larstobi** [comment]
Sweet, @mikael-lindstrom !!! 🥇 🥇 🥇

**Comment by mikael-lindstrom** [comment]
@itsdalmo Good catch, forgot about adding it to the `pipeline.yml`, will fix now.

**Comment by itsdalmo** [comment]
@mikael-lindstrom - Might want to run `fly validate-pipeline` on your end to make sure that it is a valid definition, but the changes look good to me :)

**Comment by mikael-lindstrom** [comment]
```
> fly validate-pipeline -c .ci/pipeline.yml
looks good
```
Then I'll merge and do a new release.

**Pull request merged**
