### PR TITLE
Ecs sg rds access

### PR DESCRIPTION
**Pull request by lukaspour**
Add SG which allows connection only from ECS. This [PR](https://github.com/TeliaSoneraNorge/devops/pull/377) needs to merged to make this work

### CODE REVIEW

**Comment by mikael-lindstrom** [comment]
Wouldn't it be easier to simply expose the security group and just do this connection when calling the module instead of inside this module? We are now adding ECS specific things in the RDS module which is supposed to be generic.

Also the remote state lookups will have to be removed at some point since this module should be usable regardless of how we structure our state files.

**Comment by lukaspour** [comment]
Well the problem is that at first we had `module` specific for our usage in our `devops` folder. Then I understood we should push everything in this repository. Now I would have to create again module which would use this module and add the security group from the remote state which is project specific.

Since there was already the remote state for VPC I thought that would be a problem. So you suggest to use the separate module instead?

**Comment by antonbabenko** [comment]
I agree with @mikael-lindstrom.

VPC is an essential part of this RDS module, so it can stay here, but ECS is too specific and should not be part of this open-source module.

**Comment by lukaspour** [comment]
@antonbabenko  so should I create new `neo-rds` module in `devops/terraform/modules` which would use this functionality? Or where should I put this.

**Comment by antonbabenko** [comment]
Yes, you can do it like you are saying. It is the best way. Also change `rds-instance-full/main.tf` to accept id of the security group [here](https://github.com/TeliaSoneraNorge/telia-terraform-modules/pull/61/files#diff-cc5edd63f2a912b9551970928b71aab8R70) instead of using data source terraform_remote_state

**Comment by mikael-lindstrom** [comment]
I agree with Anton, will be a much cleaner solution 👍

**Comment by lukaspour** [comment]
Ok, thanks!

**Pull request closed without merging**
