### PR TITLE
add variables required to make this standalone

### PR DESCRIPTION
**Pull request by colincoleman**

### CODE REVIEW

**Comment by antonbabenko** [comment]
This PR a bad idea because we add these variables using Terragrunt hooks and now we have broken builds where these modules are being used (for example, https://circleci.com/gh/TeliaSoneraNorge/devops/2823), so let's revert this and keep this variables missing, but rely on Terragrunt to actually prepare the code of this module.

**Comment by mikael-lindstrom** [comment]
Ideally we should remove these variables for the modules completely so we are not dependant on Terragrunt. For example these modules cannot be used in any DivX project since our state is encrypted with KMS and not S3 SSE. Not sure how hard that will be since from the circleci link it seems like some projects are not using versioning for the modules.

Also I don't think Colin has access to circleci to check the build you linked, could you grant him access @antonbabenko ?

**Comment by antonbabenko** [comment]
Everybody who has access to this repo has access to circleci as well. There is no separate access control.

The modules we are using with Terragrunt (like ALB and RDS one) require `main_variables.tf` which should be copied either using Terragrunt hooks (automatically, see `after_hook` in `terraform.tfvars`) or manually if a person wants to use those modules without Terragrunt.

Versioning is not enabled for most of them now, because there was no version in the new repository which they can refer to, but it will be changing as we speak and release new versions.

**Comment by mikael-lindstrom** [comment]
Great, is there a slack channel which circleci posts failures to?

Since I'm not familiar with the Terragrunt setup in the devops repo, would it be possible to refactor this to remove the dependency for `main_variables.tf` in the modules? Would be great if we could have the modules completely standalone.

I'd say for now we should revert this to unbreak the devops repo and then focus on switching to using versions in the devops repo. The we can figure out how to refactor this going forward.

**Comment by antonbabenko** [comment]
No, there is no such _noisy channel_. :) CircleCI reports are visible on individual PRs.

Alternatively we can add `main_variables.tf` into each module but I agree we should just get things working as they were before improving further.

**Comment by mikael-lindstrom** [comment]
Shouldn't be that noisy unless we break things :) but I guess if we do changes here and it breaks devops someone will scream.

Lets revert this and create another issue where we can discuss the way forward.

**Comment by antonbabenko** [comment]
Yes, there is no relation between this repo and places where these modules are used, so we need to rely on developers to scream loud. :)

**Pull request merged**
